export default {
  additional_info: 'Additional Information',
  customer_info_changed:
    'Please enter information if the customer has changed. Skip this screen if customer information has not changed  ',
  other_nationality: 'Other Nationality',
  select_nationality: '- Select-',
  status_residence: 'Residence Status',
  choose_other_nationality: '- Choose another nationality -  ',
  tax_code: 'Personal tax code',
  placeholder_tax_code: 'Enter your personal tax code  ',
  current_occupation: 'Current occupation  ',
  career: '- Choose a career -  ',
  position: 'Position',
  placeholder_position: '- Select a position -',
  nationality: 'Nationality',
  job: 'Job',
  other_occupation: 'Other occupation',
  other_job_title: 'Other job title',
  address: 'Address',
  contact: 'Contact',
  foreignAddress: 'Foreign Address',
  foreignPlaceholder: 'Enter a foreign address  ',
  city: 'Province/City  ',
  selectCity: '- Select -',
  district: 'District',
  selectDistrict: '- Select -  ',
  ward: 'Commune/ward/town  ',
  wardPlaceholder: '- Select -  ',
  detailAddress: 'Detailed address',
  detailedAddressPlaceholder: 'Enter detailed address  ',
  time: 'Time at address',
  placeholderTime: 'Enter time at current address',
  mobile: 'Mobile phone  ',
  placeholderPhone: 'Enter contact phone (mobile)',
  landline: 'Landline phone',
  placeholderLandline: 'Enter contact phone (landline)  ',
  email: 'Email (email)  ',
  placeholderEmail: 'Enter email  ',
  next: 'Next',
  haveResidencey: 'Have a residency',
  homeless: 'Homeless',
  otherInfo: 'Other Information',
  economyCode: 'Economic industry code',
  classLevel: 'Class level',
  otherIndividual: 'Other individuals',
  informationResident: 'Information resident',
  servicesPriority: 'Priority use to register products and services at Vietcombank ',
  debitCreditInfo:
    'Default register for VCB Digibank service and/or receive Debit Card, OTP service information from Vietcombank',
  errorMessagePhone: 'Mobile phone should have 10 digits',
  errorPhoneSpecialCharacters: 'Số điện thoại sai định dạng',
  errorPhone: 'Mobile phone is required',
  emailFormatError: 'email has incorrect format, pls check again',
  cityError: 'Please select city/province',
  districtError: 'Please select district',
  communeError: 'Please select commune',
  detailAddressError: 'Please enter detail address',
  currentAddressTime: 'Please select current address time',
  occupationError: 'Please select occupation',
  jobTitle: 'Please select job title',
  termsResidence: 'Invalid inputed date. Please input again. ',
  termsResidenceEmpError: 'Please enter term of residence',
  mobileFormat: 'Phone number starts by 0',
  landlineError: 'Landline phone should have 9-12 digits',
  occupationOtherError: 'Please enter occupation',
  jobTitleOtherError: 'Please enter job title',
  come_back: 'Come Back',
  stopExecution: 'Stop Execution',
  landlineFormat: 'Landline phone starts with 0',
  foreignAddressError: 'Please enter foreign address',
  timeAtCurrentAddressError: 'Invalid inputed date. Please input again.',
  timeAtCurrentAddressEmpError: 'Please enter time at current address ',
  economicSectorError: 'Please enter economic sector',
  classLevelCodeError: 'Please enter class level',
  update: 'Update',
  selectDate: 'Select Date',
  confirmDate: 'Confirm',
  emailError: 'Please enter email',
  fromMonth: '(from month)',
  belowheading: 'hiện tại',
  search: 'Search',
  address_80_chars_max: 'Address must be less than 80 characters',
};
