export default {
  additional_info: 'Thông tin bổ sung',
  customer_info_changed:
    'Vui lòng nhập thông tin nếu khách hàng có thay đổi. Bỏ qua màn hình này nếu thông tin khách hàng không thay đổi',
  other_nationality: 'Quốc tịch khác',
  select_nationality: '- Chọn -',
  status_residence: 'Tình trạng cư trú',
  choose_other_nationality: '- Chọn quốc tịch khác -',
  tax_code: 'Mã số thuế cá nhân',
  placeholder_tax_code: 'Nhập mã số thuế cá nhân',
  current_occupation: 'Nghề nghiệp hiện tại',
  career: '- Chọn -',
  position: 'Chức vụ',
  placeholder_position: '- Chọn -',
  nationality: 'Quốc tịch',
  job: 'Nghề nghiệp',
  other_occupation: 'Nghề nghiệp khác',
  other_job_title: 'Chức vụ khác',
  address: 'Địa chỉ',
  contact: 'Liên hệ',
  foreignAddress: 'Địa chỉ nước ngoài',
  foreignPlaceholder: 'Nhập địa chỉ nước ngoài',
  city: 'Tỉnh/Thành phố',
  selectCity: '- Chọn -',
  district: 'Quận/Huyện',
  selectDistrict: '- Chọn -',
  ward: 'Xã/phường/thị trấn',
  detailAddress: 'Địa chỉ chi tiết',
  wardPlaceholder: '- Chọn -',
  detailedAddressPlaceholder: 'Nhập địa chỉ chi tiết',
  timeSelect: 'Thời gian ở địa chỉ',
  time: 'Thời gian ở địa chỉ  hiện tại   (từ tháng)',
  time_vn: 'Thời hạn cư trú tại Việt Nam',
  placeholderTime: 'Nhập địa chỉ chi tiết',
  mobile: 'Điện thoại di động',
  placeholderPhone: 'Nhập điện thoại liên hệ (di động)',
  landline: 'Điện thoại cố định',
  landline1: 'Địa chỉ nước ngoài',
  placeholderLandline: 'Nhập điện thoại liên hệ (cố định)',
  email: 'Thư điện tử (email)',
  placeholderEmail: 'Nhập thư điện tử',
  next: 'Tiếp tục',
  haveResidencey: 'Có cư trú',
  homeless: 'Không cư trú',
  otherInfo: 'Thông tin khác',
  economyCode: 'Mã ngành nghề kinh tế',
  classLevel: 'Class level',
  otherIndividual: 'Cá nhân khác',
  informationResident: 'Thông tin cư trú',
  servicesPriority: 'Ưu tiên sử dụng để đăng ký các sản phẩm dịch vụ tại Vietcombank',
  debitCreditInfo:
    'Mặc định đăng ký dịch vụ VCB Digibank và/hoặc nhận thông tin dịch vụ Thẻ ghi nợ, OTP từ Vietcombank',
  errorMessagePhone: 'Điện thoại di động cần có 10 chữ số',
  errorPhoneSpecialCharacters: 'Số điện thoại sai định dạng',
  errorPhone: 'Điện thoại di động là bắt buộc    ',
  emailFormatError: 'Thư điện tử không đúng định dạng. Vui lòng kiểm tra lại',
  cityError: 'Vui lòng chọn thành phố/tỉnh',
  districtError: 'Vui lòng chọn huyện',
  communeError: 'Vui lòng chọn xã ',
  detailAddressError: 'Vui lòng nhập địa chỉ chi tiết',
  currentAddressTime: 'Vui lòng chọn thời gian địa chỉ hiện tại    ',
  occupationError: 'Vui lòng chọn nghề nghiệp',
  occupationOtherError: 'Vui lòng ghi rõ nghề nghiệp khác',
  jobTitle: 'Vui lòng chọn chức danh công việc',
  jobTitleOtherError: 'Vui lòng ghi rõ chức vụ khác',
  termsResidence: 'Ngày nhập không hợp lệ. Vui lòng nhập lại. ',
  termsResidenceEmpError: 'Vui lòng nhập thời hạn cư trú',
  mobileFormat: 'Điện thoại di động bắt đầu bằng 0',
  landlineError: 'Điện thoại cố định cần có 9-12 chữ số',
  come_back: 'Quay lại',
  stopExecution: 'Dừng thực hiện',
  landlineFormat: 'Điện thoại cố định bắt đầu bằng 0  ',
  foreignAddressError: 'Vui lòng nhập địa chỉ nước ngoài',
  timeAtCurrentAddressError: 'Ngày nhập không hợp lệ. Vui lòng nhập lại.  ',
  timeAtCurrentAddressEmpError: 'Vui lòng nhập thời gian tại địa chỉ hiện tại  ',
  economicSectorError: 'Vui lòng chọn ngành kinh tế',
  classLevelCodeError: 'Vui lòng chọn Class level',
  update: 'cập nhật  ',
  selectDate: 'Chọn ngày',
  confirmDate: 'Xác nhận',
  emailError: 'Vui lòng nhập email',
  fromMonth: '(từ tháng)',
  belowheading: 'hiện tại',
  search: 'Tìm kiếm',
  address_80_chars_max:
    'Địa chỉ hiện tại vượt quá 80 ký tự. Vui lòng điều chỉnh trường Địa chỉ chi tiết',
};
