export const TestIds = {
  user_info_modal: 'user_info_modal',
  modal_image_icon: 'modal_image_icon',
  name_id: 'name_id',
  type_id: 'type_id',
  profession_id: 'profession_id',
  logout_button_id: 'logout_button_id',
  logout_button_text_id: 'logout_button_text_id',
  profile_icon: 'profile_icon',
  logo_test_id: 'logo_test_id',
  heading: 'heading',
  check_existence_button: 'check_existence_button',
  button_text: 'button_text',
  transaction_heading: 'transaction_heading',
  close_modal: 'close_modal',
  cancel_modal: 'cancel_modal',
  onboarding_option: 'onboarding_option',
  item_name: 'item_name',
};
