export enum ROUTES {
  APP_NAVIGATION = "APP_NAVIGATION",
  GUEST_NAVIGATION = "GUEST_NAVIGATION",
}

export enum EAppScreenList {
  HOME_STACK_SCREEN = "HOME_STACK_SCREEN",
}

export enum EGuestScreenList {
  FIRST_SCREEN = "FIRST_SCREEN",
}

export enum EHomeScreenList {
  HOME_SCREEN = "HOME_SCREEN",
  HOME_DETAIL_SCREEN = "HOME_DETAIL_SCREEN",
}
