export default {
  group1: require('../../../assets/images/icons/group1.png'),
  group2: require('../../../assets/images/icons/group2.png'),
  group3: require('../../../assets/images/icons/group3.png'),
  group4: require('../../../assets/images/icons/group4.png'),
  document: require('../../../assets/images/icons/document_text.png'),
  un_checked: require('../../../assets/images/icons/un_checked.png'),
  checked: require('../../../assets/images/icons/checked.png'),
  search: require('../../../assets/images/icons/search.png'),
  green_plus: require('../../../assets/images/icons/green_plus.png'),
  green_tick: require('../../../assets/images/icons/green_tick.png'),
  edit_grey: require('../../../assets/images/icons/edit_grey.png'),
  trash: require('../../../assets/images/icons/trash.png'),
  success: require('../../../assets/images/icons/checked_circle.png'),
  clear: require('../../../assets/images/icons/close.png'),
  selectedRadio:require('../../../assets/images/icons/selectedRadio.png'),
  unSelectedRadio:require('../../../assets/images/icons/unselectRadio.png'),
  switch_off: require('../../../assets/images/onboarding/toggle_off.png'),
  switch_on: require('../../../assets/images/onboarding/toggle_on.png'),
  red_error: require('../../../assets/images/onboarding/Frame.png'),

};
