export interface INation {
  name: string;
  code: string;
  emoji: string;
  dial_code: string;
  label: string;
}

const PHONE_CODES_AND_LINKS: INation[] = [
  {
    name: "Canada",
    code: "CA",
    emoji: "🇨🇦",
    dial_code: "+1",
    label: "🇨🇦 +1",
  },
  {
    name: "United States",
    code: "US",
    emoji: "🇺🇸",
    dial_code: "+1",
    label: "🇺🇸 +1",
  },
  {
    name: "Russia",
    code: "RU",
    emoji: "🇷🇺",
    dial_code: "+7",
    label: "🇷🇺 +7",
  },
  {
    name: "Egypt",
    code: "EG",
    emoji: "🇪🇬",
    dial_code: "+20",
    label: "🇪🇬 +20",
  },
  {
    name: "South Africa",
    code: "ZA",
    emoji: "🇿🇦",
    dial_code: "+27",
    label: "🇿🇦 +27",
  },
  {
    name: "Greece",
    code: "GR",
    emoji: "🇬🇷",
    dial_code: "+30",
    label: "🇬🇷 +30",
  },
  {
    name: "Netherlands",
    code: "NL",
    emoji: "🇳🇱",
    dial_code: "+31",
    label: "🇳🇱 +31",
  },
  {
    name: "Belgium",
    code: "BE",
    emoji: "🇧🇪",
    dial_code: "+32",
    label: "🇧🇪 +32",
  },
  {
    name: "France",
    code: "FR",
    emoji: "🇫🇷",
    dial_code: "+33",
    label: "🇫🇷 +33",
  },
  {
    name: "Spain",
    code: "ES",
    emoji: "🇪🇸",
    dial_code: "+34",
    label: "🇪🇸 +34",
  },
  {
    name: "Hungary",
    code: "HU",
    emoji: "🇭🇺",
    dial_code: "+36",
    label: "🇭🇺 +36",
  },
  {
    name: "Italy",
    code: "IT",
    emoji: "🇮🇹",
    dial_code: "+39",
    label: "🇮🇹 +39",
  },
  {
    name: "Romania",
    code: "RO",
    emoji: "🇷🇴",
    dial_code: "+40",
    label: "🇷🇴 +40",
  },
  {
    name: "Switzerland",
    code: "CH",
    emoji: "🇨🇭",
    dial_code: "+41",
    label: "🇨🇭 +41",
  },
  {
    name: "Austria",
    code: "AT",
    emoji: "🇦🇹",
    dial_code: "+43",
    label: "🇦🇹 +43",
  },
  {
    name: "Guernsey",
    code: "GG",
    emoji: "🇬🇬",
    dial_code: "+44",
    label: "🇬🇬 +44",
  },
  {
    name: "Isle of Man",
    code: "IM",
    emoji: "🇮🇲",
    dial_code: "+44",
    label: "🇮🇲 +44",
  },
  {
    name: "Jersey",
    code: "JE",
    emoji: "🇯🇪",
    dial_code: "+44",
    label: "🇯🇪 +44",
  },
  {
    name: "United Kingdom",
    code: "UK",
    emoji: "🇬🇧",
    dial_code: "+44",
    label: "🇬🇧 +44",
  },
  {
    name: "Denmark",
    code: "DK",
    emoji: "🇩🇰",
    dial_code: "+45",
    label: "🇩🇰 +45",
  },
  {
    name: "Sweden",
    code: "SE",
    emoji: "🇸🇪",
    dial_code: "+46",
    label: "🇸🇪 +46",
  },
  {
    name: "Norway",
    code: "NO",
    emoji: "🇳🇴",
    dial_code: "+47",
    label: "🇳🇴 +47",
  },
  {
    name: "Svalbard & Jan Mayen",
    code: "SJ",
    emoji: "🇸🇯",
    dial_code: "+47",
    label: "🇸🇯 +47",
  },
  {
    name: "Poland",
    code: "PL",
    emoji: "🇵🇱",
    dial_code: "+48",
    label: "🇵🇱 +48",
  },
  {
    name: "Germany",
    code: "DE",
    emoji: "🇩🇪",
    dial_code: "+49",
    label: "🇩🇪 +49",
  },
  {
    name: "Peru",
    code: "PE",
    emoji: "🇵🇪",
    dial_code: "+51",
    label: "🇵🇪 +51",
  },
  {
    name: "Mexico",
    code: "MX",
    emoji: "🇲🇽",
    dial_code: "+52",
    label: "🇲🇽 +52",
  },
  {
    name: "Cuba",
    code: "CU",
    emoji: "🇨🇺",
    dial_code: "+53",
    label: "🇨🇺 +53",
  },
  {
    name: "Argentina",
    code: "AR",
    emoji: "🇦🇷",
    dial_code: "+54",
    label: "🇦🇷 +54",
  },
  {
    name: "Brazil",
    code: "BR",
    emoji: "🇧🇷",
    dial_code: "+55",
    label: "🇧🇷 +55",
  },
  {
    name: "Chile",
    code: "CL",
    emoji: "🇨🇱",
    dial_code: "+56",
    label: "🇨🇱 +56",
  },
  {
    name: "Colombia",
    code: "CO",
    emoji: "🇨🇴",
    dial_code: "+57",
    label: "🇨🇴 +57",
  },
  {
    name: "Venezuela",
    code: "VE",
    emoji: "🇻🇪",
    dial_code: "+58",
    label: "🇻🇪 +58",
  },
  {
    name: "Malaysia",
    code: "MY",
    emoji: "🇲🇾",
    dial_code: "+60",
    label: "🇲🇾 +60",
  },
  {
    name: "Australia",
    code: "AU",
    emoji: "🇦🇺",
    dial_code: "+61",
    label: "🇦🇺 +61",
  },
  {
    name: "Christmas Island",
    code: "CX",
    emoji: "🇨🇽",
    dial_code: "+61",
    label: "🇨🇽 +61",
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    emoji: "🇨🇨",
    dial_code: "+61",
    label: "🇨🇨 +61",
  },
  {
    name: "Indonesia",
    code: "ID",
    emoji: "🇮🇩",
    dial_code: "+62",
    label: "🇮🇩 +62",
  },
  {
    name: "Philippines",
    code: "PH",
    emoji: "🇵🇭",
    dial_code: "+63",
    label: "🇵🇭 +63",
  },
  {
    name: "New Zealand",
    code: "NZ",
    emoji: "🇳🇿",
    dial_code: "+64",
    label: "🇳🇿 +64",
  },
  {
    name: "Singapore",
    code: "SG",
    emoji: "🇸🇬",
    dial_code: "+65",
    label: "🇸🇬 +65",
  },
  {
    name: "Thailand",
    code: "TH",
    emoji: "🇹🇭",
    dial_code: "+66",
    label: "🇹🇭 +66",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    emoji: "🇰🇿",
    dial_code: "+77",
    label: "🇰🇿 +77",
  },
  {
    name: "Japan",
    code: "JP",
    emoji: "🇯🇵",
    dial_code: "+81",
    label: "🇯🇵 +81",
  },
  {
    name: "South Korea",
    code: "KR",
    emoji: "🇰🇷",
    dial_code: "+82",
    label: "🇰🇷 +82",
  },
  {
    name: "Vietnam",
    code: "VN",
    emoji: "🇻🇳",
    dial_code: "+84",
    label: "🇻🇳 +84",
  },
  {
    name: "China",
    code: "CN",
    emoji: "🇨🇳",
    dial_code: "+86",
    label: "🇨🇳 +86",
  },
  {
    name: "Turkey",
    code: "TR",
    emoji: "🇹🇷",
    dial_code: "+90",
    label: "🇹🇷 +90",
  },
  {
    name: "India",
    code: "IN",
    emoji: "🇮🇳",
    dial_code: "+91",
    label: "🇮🇳 +91",
  },
  {
    name: "Pakistan",
    code: "PK",
    emoji: "🇵🇰",
    dial_code: "+92",
    label: "🇵🇰 +92",
  },
  {
    name: "Afghanistan",
    code: "AF",
    emoji: "🇦🇫",
    dial_code: "+93",
    label: "🇦🇫 +93",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    emoji: "🇱🇰",
    dial_code: "+94",
    label: "🇱🇰 +94",
  },
  {
    name: "Myanmar (Burma)",
    code: "MM",
    emoji: "🇲🇲",
    dial_code: "+95",
    label: "🇲🇲 +95",
  },
  {
    name: "Iran",
    code: "IR",
    emoji: "🇮🇷",
    dial_code: "+98",
    label: "🇮🇷 +98",
  },
  {
    name: "South Sudan",
    code: "SS",
    emoji: "🇸🇸",
    dial_code: "+211",
    label: "🇸🇸 +211",
  },
  {
    name: "Morocco",
    code: "MA",
    emoji: "🇲🇦",
    dial_code: "+212",
    label: "🇲🇦 +212",
  },
  {
    name: "Algeria",
    code: "DZ",
    emoji: "🇩🇿",
    dial_code: "+213",
    label: "🇩🇿 +213",
  },
  {
    name: "Tunisia",
    code: "TN",
    emoji: "🇹🇳",
    dial_code: "+216",
    label: "🇹🇳 +216",
  },
  {
    name: "Libya",
    code: "LY",
    emoji: "🇱🇾",
    dial_code: "+218",
    label: "🇱🇾 +218",
  },
  {
    name: "Gambia",
    code: "GM",
    emoji: "🇬🇲",
    dial_code: "+220",
    label: "🇬🇲 +220",
  },
  {
    name: "Senegal",
    code: "SN",
    emoji: "🇸🇳",
    dial_code: "+221",
    label: "🇸🇳 +221",
  },
  {
    name: "Mauritania",
    code: "MR",
    emoji: "🇲🇷",
    dial_code: "+222",
    label: "🇲🇷 +222",
  },
  {
    name: "Mali",
    code: "ML",
    emoji: "🇲🇱",
    dial_code: "+223",
    label: "🇲🇱 +223",
  },
  {
    name: "Guinea",
    code: "GN",
    emoji: "🇬🇳",
    dial_code: "+224",
    label: "🇬🇳 +224",
  },
  {
    name: "Côte d’Ivoire",
    code: "CI",
    emoji: "🇨🇮",
    dial_code: "+225",
    label: "🇨🇮 +225",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    emoji: "🇧🇫",
    dial_code: "+226",
    label: "🇧🇫 +226",
  },
  {
    name: "Niger",
    code: "NE",
    emoji: "🇳🇪",
    dial_code: "+227",
    label: "🇳🇪 +227",
  },
  {
    name: "Togo",
    code: "TG",
    emoji: "🇹🇬",
    dial_code: "+228",
    label: "🇹🇬 +228",
  },
  {
    name: "Benin",
    code: "BJ",
    emoji: "🇧🇯",
    dial_code: "+229",
    label: "🇧🇯 +229",
  },
  {
    name: "Mauritius",
    code: "MU",
    emoji: "🇲🇺",
    dial_code: "+230",
    label: "🇲🇺 +230",
  },
  {
    name: "Liberia",
    code: "LR",
    emoji: "🇱🇷",
    dial_code: "+231",
    label: "🇱🇷 +231",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    emoji: "🇸🇱",
    dial_code: "+232",
    label: "🇸🇱 +232",
  },
  {
    name: "Ghana",
    code: "GH",
    emoji: "🇬🇭",
    dial_code: "+233",
    label: "🇬🇭 +233",
  },
  {
    name: "Nigeria",
    code: "NG",
    emoji: "🇳🇬",
    dial_code: "+234",
    label: "🇳🇬 +234",
  },
  {
    name: "Chad",
    code: "TD",
    emoji: "🇹🇩",
    dial_code: "+235",
    label: "🇹🇩 +235",
  },
  {
    name: "Central African Republic",
    code: "CF",
    emoji: "🇨🇫",
    dial_code: "+236",
    label: "🇨🇫 +236",
  },
  {
    name: "Cameroon",
    code: "CM",
    emoji: "🇨🇲",
    dial_code: "+237",
    label: "🇨🇲 +237",
  },
  {
    name: "Cape Verde",
    code: "CV",
    emoji: "🇨🇻",
    dial_code: "+238",
    label: "🇨🇻 +238",
  },
  {
    name: "São Tomé & Príncipe",
    code: "ST",
    emoji: "🇸🇹",
    dial_code: "+239",
    label: "🇸🇹 +239",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    emoji: "🇬🇶",
    dial_code: "+240",
    label: "🇬🇶 +240",
  },
  {
    name: "Gabon",
    code: "GA",
    emoji: "🇬🇦",
    dial_code: "+241",
    label: "🇬🇦 +241",
  },
  {
    name: "Congo - Brazzaville",
    code: "CG",
    emoji: "🇨🇬",
    dial_code: "+242",
    label: "🇨🇬 +242",
  },
  {
    name: "Congo - Kinshasa",
    code: "CD",
    emoji: "🇨🇩",
    dial_code: "+243",
    label: "🇨🇩 +243",
  },
  {
    name: "Angola",
    code: "AO",
    emoji: "🇦🇴",
    dial_code: "+244",
    label: "🇦🇴 +244",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    emoji: "🇬🇼",
    dial_code: "+245",
    label: "🇬🇼 +245",
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    emoji: "🇮🇴",
    dial_code: "+246",
    label: "🇮🇴 +246",
  },
  {
    name: "Seychelles",
    code: "SC",
    emoji: "🇸🇨",
    dial_code: "+248",
    label: "🇸🇨 +248",
  },
  {
    name: "Sudan",
    code: "SD",
    emoji: "🇸🇩",
    dial_code: "+249",
    label: "🇸🇩 +249",
  },
  {
    name: "Rwanda",
    code: "RW",
    emoji: "🇷🇼",
    dial_code: "+250",
    label: "🇷🇼 +250",
  },
  {
    name: "Ethiopia",
    code: "ET",
    emoji: "🇪🇹",
    dial_code: "+251",
    label: "🇪🇹 +251",
  },
  {
    name: "Somalia",
    code: "SO",
    emoji: "🇸🇴",
    dial_code: "+252",
    label: "🇸🇴 +252",
  },
  {
    name: "Djibouti",
    code: "DJ",
    emoji: "🇩🇯",
    dial_code: "+253",
    label: "🇩🇯 +253",
  },
  {
    name: "Kenya",
    code: "KE",
    emoji: "🇰🇪",
    dial_code: "+254",
    label: "🇰🇪 +254",
  },
  {
    name: "Tanzania",
    code: "TZ",
    emoji: "🇹🇿",
    dial_code: "+255",
    label: "🇹🇿 +255",
  },
  {
    name: "Uganda",
    code: "UG",
    emoji: "🇺🇬",
    dial_code: "+256",
    label: "🇺🇬 +256",
  },
  {
    name: "Burundi",
    code: "BI",
    emoji: "🇧🇮",
    dial_code: "+257",
    label: "🇧🇮 +257",
  },
  {
    name: "Mozambique",
    code: "MZ",
    emoji: "🇲🇿",
    dial_code: "+258",
    label: "🇲🇿 +258",
  },
  {
    name: "Zambia",
    code: "ZM",
    emoji: "🇿🇲",
    dial_code: "+260",
    label: "🇿🇲 +260",
  },
  {
    name: "Madagascar",
    code: "MG",
    emoji: "🇲🇬",
    dial_code: "+261",
    label: "🇲🇬 +261",
  },
  {
    name: "Mayotte",
    code: "YT",
    emoji: "🇾🇹",
    dial_code: "+262",
    label: "🇾🇹 +262",
  },
  {
    name: "Réunion",
    code: "RE",
    emoji: "🇷🇪",
    dial_code: "+262",
    label: "🇷🇪 +262",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    emoji: "🇿🇼",
    dial_code: "+263",
    label: "🇿🇼 +263",
  },
  {
    name: "Namibia",
    code: "NA",
    emoji: "🇳🇦",
    dial_code: "+264",
    label: "🇳🇦 +264",
  },
  {
    name: "Malawi",
    code: "MW",
    emoji: "🇲🇼",
    dial_code: "+265",
    label: "🇲🇼 +265",
  },
  {
    name: "Lesotho",
    code: "LS",
    emoji: "🇱🇸",
    dial_code: "+266",
    label: "🇱🇸 +266",
  },
  {
    name: "Botswana",
    code: "BW",
    emoji: "🇧🇼",
    dial_code: "+267",
    label: "🇧🇼 +267",
  },
  {
    name: "Eswatini",
    code: "SZ",
    emoji: "🇸🇿",
    dial_code: "+268",
    label: "🇸🇿 +268",
  },
  {
    name: "Comoros",
    code: "KM",
    emoji: "🇰🇲",
    dial_code: "+269",
    label: "🇰🇲 +269",
  },
  {
    name: "St. Helena",
    code: "SH",
    emoji: "🇸🇭",
    dial_code: "+290",
    label: "🇸🇭 +290",
  },
  {
    name: "Eritrea",
    code: "ER",
    emoji: "🇪🇷",
    dial_code: "+291",
    label: "🇪🇷 +291",
  },
  {
    name: "Aruba",
    code: "AW",
    emoji: "🇦🇼",
    dial_code: "+297",
    label: "🇦🇼 +297",
  },
  {
    name: "Faroe Islands",
    code: "FO",
    emoji: "🇫🇴",
    dial_code: "+298",
    label: "🇫🇴 +298",
  },
  {
    name: "Greenland",
    code: "GL",
    emoji: "🇬🇱",
    dial_code: "+299",
    label: "🇬🇱 +299",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    emoji: "🇰🇾",
    dial_code: "+ 345",
    label: "🇰🇾 + 345",
  },
  {
    name: "Gibraltar",
    code: "GI",
    emoji: "🇬🇮",
    dial_code: "+350",
    label: "🇬🇮 +350",
  },
  {
    name: "Portugal",
    code: "PT",
    emoji: "🇵🇹",
    dial_code: "+351",
    label: "🇵🇹 +351",
  },
  {
    name: "Luxembourg",
    code: "LU",
    emoji: "🇱🇺",
    dial_code: "+352",
    label: "🇱🇺 +352",
  },
  {
    name: "Ireland",
    code: "IE",
    emoji: "🇮🇪",
    dial_code: "+353",
    label: "🇮🇪 +353",
  },
  {
    name: "Iceland",
    code: "IS",
    emoji: "🇮🇸",
    dial_code: "+354",
    label: "🇮🇸 +354",
  },
  {
    name: "Albania",
    code: "AL",
    emoji: "🇦🇱",
    dial_code: "+355",
    label: "🇦🇱 +355",
  },
  {
    name: "Malta",
    code: "MT",
    emoji: "🇲🇹",
    dial_code: "+356",
    label: "🇲🇹 +356",
  },
  {
    name: "Cyprus",
    code: "CY",
    emoji: "🇨🇾",
    dial_code: "+357",
    label: "🇨🇾 +357",
  },
  {
    name: "Finland",
    code: "FI",
    emoji: "🇫🇮",
    dial_code: "+358",
    label: "🇫🇮 +358",
  },
  {
    name: "Åland Islands",
    code: "AX",
    emoji: "🇦🇽",
    dial_code: "+358",
    label: "🇦🇽 +358",
  },
  {
    name: "Bulgaria",
    code: "BG",
    emoji: "🇧🇬",
    dial_code: "+359",
    label: "🇧🇬 +359",
  },
  {
    name: "Lithuania",
    code: "LT",
    emoji: "🇱🇹",
    dial_code: "+370",
    label: "🇱🇹 +370",
  },
  {
    name: "Latvia",
    code: "LV",
    emoji: "🇱🇻",
    dial_code: "+371",
    label: "🇱🇻 +371",
  },
  {
    name: "Estonia",
    code: "EE",
    emoji: "🇪🇪",
    dial_code: "+372",
    label: "🇪🇪 +372",
  },
  {
    name: "Moldova",
    code: "MD",
    emoji: "🇲🇩",
    dial_code: "+373",
    label: "🇲🇩 +373",
  },
  {
    name: "Armenia",
    code: "AM",
    emoji: "🇦🇲",
    dial_code: "+374",
    label: "🇦🇲 +374",
  },
  {
    name: "Belarus",
    code: "BY",
    emoji: "🇧🇾",
    dial_code: "+375",
    label: "🇧🇾 +375",
  },
  {
    name: "Andorra",
    code: "AD",
    emoji: "🇦🇩",
    dial_code: "+376",
    label: "🇦🇩 +376",
  },
  {
    name: "Monaco",
    code: "MC",
    emoji: "🇲🇨",
    dial_code: "+377",
    label: "🇲🇨 +377",
  },
  {
    name: "San Marino",
    code: "SM",
    emoji: "🇸🇲",
    dial_code: "+378",
    label: "🇸🇲 +378",
  },
  {
    name: "Vatican City",
    code: "VA",
    emoji: "🇻🇦",
    dial_code: "+379",
    label: "🇻🇦 +379",
  },
  {
    name: "Ukraine",
    code: "UA",
    emoji: "🇺🇦",
    dial_code: "+380",
    label: "🇺🇦 +380",
  },
  {
    name: "Serbia",
    code: "RS",
    emoji: "🇷🇸",
    dial_code: "+381",
    label: "🇷🇸 +381",
  },
  {
    name: "Montenegro",
    code: "ME",
    emoji: "🇲🇪",
    dial_code: "+382",
    label: "🇲🇪 +382",
  },
  {
    name: "Croatia",
    code: "HR",
    emoji: "🇭🇷",
    dial_code: "+385",
    label: "🇭🇷 +385",
  },
  {
    name: "Slovenia",
    code: "SI",
    emoji: "🇸🇮",
    dial_code: "+386",
    label: "🇸🇮 +386",
  },
  {
    name: "Bosnia & Herzegovina",
    code: "BA",
    emoji: "🇧🇦",
    dial_code: "+387",
    label: "🇧🇦 +387",
  },
  {
    name: "North Macedonia",
    code: "MK",
    emoji: "🇲🇰",
    dial_code: "+389",
    label: "🇲🇰 +389",
  },
  {
    name: "Czechia",
    code: "CZ",
    emoji: "🇨🇿",
    dial_code: "+420",
    label: "🇨🇿 +420",
  },
  {
    name: "Slovakia",
    code: "SK",
    emoji: "🇸🇰",
    dial_code: "+421",
    label: "🇸🇰 +421",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    emoji: "🇱🇮",
    dial_code: "+423",
    label: "🇱🇮 +423",
  },
  {
    name: "Falkland Islands",
    code: "FK",
    emoji: "🇫🇰",
    dial_code: "+500",
    label: "🇫🇰 +500",
  },
  {
    name: "South Georgia & South Sandwich Islands",
    code: "GS",
    emoji: "🇬🇸",
    dial_code: "+500",
    label: "🇬🇸 +500",
  },
  {
    name: "Belize",
    code: "BZ",
    emoji: "🇧🇿",
    dial_code: "+501",
    label: "🇧🇿 +501",
  },
  {
    name: "Guatemala",
    code: "GT",
    emoji: "🇬🇹",
    dial_code: "+502",
    label: "🇬🇹 +502",
  },
  {
    name: "El Salvador",
    code: "SV",
    emoji: "🇸🇻",
    dial_code: "+503",
    label: "🇸🇻 +503",
  },
  {
    name: "Honduras",
    code: "HN",
    emoji: "🇭🇳",
    dial_code: "+504",
    label: "🇭🇳 +504",
  },
  {
    name: "Nicaragua",
    code: "NI",
    emoji: "🇳🇮",
    dial_code: "+505",
    label: "🇳🇮 +505",
  },
  {
    name: "Costa Rica",
    code: "CR",
    emoji: "🇨🇷",
    dial_code: "+506",
    label: "🇨🇷 +506",
  },
  {
    name: "Panama",
    code: "PA",
    emoji: "🇵🇦",
    dial_code: "+507",
    label: "🇵🇦 +507",
  },
  {
    name: "St. Pierre & Miquelon",
    code: "PM",
    emoji: "🇵🇲",
    dial_code: "+508",
    label: "🇵🇲 +508",
  },
  {
    name: "Haiti",
    code: "HT",
    emoji: "🇭🇹",
    dial_code: "+509",
    label: "🇭🇹 +509",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    emoji: "🇬🇵",
    dial_code: "+590",
    label: "🇬🇵 +590",
  },
  {
    name: "St. Barthélemy",
    code: "BL",
    emoji: "🇧🇱",
    dial_code: "+590",
    label: "🇧🇱 +590",
  },
  {
    name: "St. Martin",
    code: "MF",
    emoji: "🇲🇫",
    dial_code: "+590",
    label: "🇲🇫 +590",
  },
  {
    name: "Bolivia",
    code: "BO",
    emoji: "🇧🇴",
    dial_code: "+591",
    label: "🇧🇴 +591",
  },
  {
    name: "Ecuador",
    code: "EC",
    emoji: "🇪🇨",
    dial_code: "+593",
    label: "🇪🇨 +593",
  },
  {
    name: "French Guiana",
    code: "GF",
    emoji: "🇬🇫",
    dial_code: "+594",
    label: "🇬🇫 +594",
  },
  {
    name: "Guyana",
    code: "GY",
    emoji: "🇬🇾",
    dial_code: "+595",
    label: "🇬🇾 +595",
  },
  {
    name: "Paraguay",
    code: "PY",
    emoji: "🇵🇾",
    dial_code: "+595",
    label: "🇵🇾 +595",
  },
  {
    name: "Martinique",
    code: "MQ",
    emoji: "🇲🇶",
    dial_code: "+596",
    label: "🇲🇶 +596",
  },
  {
    name: "Suriname",
    code: "SR",
    emoji: "🇸🇷",
    dial_code: "+597",
    label: "🇸🇷 +597",
  },
  {
    name: "Uruguay",
    code: "UY",
    emoji: "🇺🇾",
    dial_code: "+598",
    label: "🇺🇾 +598",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    emoji: "🇹🇱",
    dial_code: "+670",
    label: "🇹🇱 +670",
  },
  {
    name: "Antarctica",
    code: "AQ",
    emoji: "🇦🇶",
    dial_code: "+672",
    label: "🇦🇶 +672",
  },
  {
    name: "Norfolk Island",
    code: "NF",
    emoji: "🇳🇫",
    dial_code: "+672",
    label: "🇳🇫 +672",
  },
  {
    name: "Brunei",
    code: "BN",
    emoji: "🇧🇳",
    dial_code: "+673",
    label: "🇧🇳 +673",
  },
  {
    name: "Nauru",
    code: "NR",
    emoji: "🇳🇷",
    dial_code: "+674",
    label: "🇳🇷 +674",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    emoji: "🇵🇬",
    dial_code: "+675",
    label: "🇵🇬 +675",
  },
  {
    name: "Tonga",
    code: "TO",
    emoji: "🇹🇴",
    dial_code: "+676",
    label: "🇹🇴 +676",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    emoji: "🇸🇧",
    dial_code: "+677",
    label: "🇸🇧 +677",
  },
  {
    name: "Vanuatu",
    code: "VU",
    emoji: "🇻🇺",
    dial_code: "+678",
    label: "🇻🇺 +678",
  },
  {
    name: "Fiji",
    code: "FJ",
    emoji: "🇫🇯",
    dial_code: "+679",
    label: "🇫🇯 +679",
  },
  {
    name: "Palau",
    code: "PW",
    emoji: "🇵🇼",
    dial_code: "+680",
    label: "🇵🇼 +680",
  },
  {
    name: "Wallis & Futuna",
    code: "WF",
    emoji: "🇼🇫",
    dial_code: "+681",
    label: "🇼🇫 +681",
  },
  {
    name: "Cook Islands",
    code: "CK",
    emoji: "🇨🇰",
    dial_code: "+682",
    label: "🇨🇰 +682",
  },
  {
    name: "Niue",
    code: "NU",
    emoji: "🇳🇺",
    dial_code: "+683",
    label: "🇳🇺 +683",
  },
  {
    name: "Samoa",
    code: "WS",
    emoji: "🇼🇸",
    dial_code: "+685",
    label: "🇼🇸 +685",
  },
  {
    name: "Kiribati",
    code: "KI",
    emoji: "🇰🇮",
    dial_code: "+686",
    label: "🇰🇮 +686",
  },
  {
    name: "New Caledonia",
    code: "NC",
    emoji: "🇳🇨",
    dial_code: "+687",
    label: "🇳🇨 +687",
  },
  {
    name: "Tuvalu",
    code: "TV",
    emoji: "🇹🇻",
    dial_code: "+688",
    label: "🇹🇻 +688",
  },
  {
    name: "French Polynesia",
    code: "PF",
    emoji: "🇵🇫",
    dial_code: "+689",
    label: "🇵🇫 +689",
  },
  {
    name: "Tokelau",
    code: "TK",
    emoji: "🇹🇰",
    dial_code: "+690",
    label: "🇹🇰 +690",
  },
  {
    name: "Micronesia",
    code: "FM",
    emoji: "🇫🇲",
    dial_code: "+691",
    label: "🇫🇲 +691",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    emoji: "🇲🇭",
    dial_code: "+692",
    label: "🇲🇭 +692",
  },
  {
    name: "North Korea",
    code: "KP",
    emoji: "🇰🇵",
    dial_code: "+850",
    label: "🇰🇵 +850",
  },
  {
    name: "Hong Kong SAR China",
    code: "HK",
    emoji: "🇭🇰",
    dial_code: "+852",
    label: "🇭🇰 +852",
  },
  {
    name: "Macao SAR China",
    code: "MO",
    emoji: "🇲🇴",
    dial_code: "+853",
    label: "🇲🇴 +853",
  },
  {
    name: "Cambodia",
    code: "KH",
    emoji: "🇰🇭",
    dial_code: "+855",
    label: "🇰🇭 +855",
  },
  {
    name: "Laos",
    code: "LA",
    emoji: "🇱🇦",
    dial_code: "+856",
    label: "🇱🇦 +856",
  },
  {
    name: "Pitcairn Islands",
    code: "PN",
    emoji: "🇵🇳",
    dial_code: "+872",
    label: "🇵🇳 +872",
  },
  {
    name: "Bangladesh",
    code: "BD",
    emoji: "🇧🇩",
    dial_code: "+880",
    label: "🇧🇩 +880",
  },
  {
    name: "Taiwan",
    code: "TW",
    emoji: "🇹🇼",
    dial_code: "+886",
    label: "🇹🇼 +886",
  },
  {
    name: "Maldives",
    code: "MV",
    emoji: "🇲🇻",
    dial_code: "+960",
    label: "🇲🇻 +960",
  },
  {
    name: "Lebanon",
    code: "LB",
    emoji: "🇱🇧",
    dial_code: "+961",
    label: "🇱🇧 +961",
  },
  {
    name: "Jordan",
    code: "JO",
    emoji: "🇯🇴",
    dial_code: "+962",
    label: "🇯🇴 +962",
  },
  {
    name: "Syria",
    code: "SY",
    emoji: "🇸🇾",
    dial_code: "+963",
    label: "🇸🇾 +963",
  },
  {
    name: "Iraq",
    code: "IQ",
    emoji: "🇮🇶",
    dial_code: "+964",
    label: "🇮🇶 +964",
  },
  {
    name: "Kuwait",
    code: "KW",
    emoji: "🇰🇼",
    dial_code: "+965",
    label: "🇰🇼 +965",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    emoji: "🇸🇦",
    dial_code: "+966",
    label: "🇸🇦 +966",
  },
  {
    name: "Yemen",
    code: "YE",
    emoji: "🇾🇪",
    dial_code: "+967",
    label: "🇾🇪 +967",
  },
  {
    name: "Oman",
    code: "OM",
    emoji: "🇴🇲",
    dial_code: "+968",
    label: "🇴🇲 +968",
  },
  {
    name: "Palestinian Territories",
    code: "PS",
    emoji: "🇵🇸",
    dial_code: "+970",
    label: "🇵🇸 +970",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    emoji: "🇦🇪",
    dial_code: "+971",
    label: "🇦🇪 +971",
  },
  {
    name: "Israel",
    code: "IL",
    emoji: "🇮🇱",
    dial_code: "+972",
    label: "🇮🇱 +972",
  },
  {
    name: "Bahrain",
    code: "BH",
    emoji: "🇧🇭",
    dial_code: "+973",
    label: "🇧🇭 +973",
  },
  {
    name: "Qatar",
    code: "QA",
    emoji: "🇶🇦",
    dial_code: "+974",
    label: "🇶🇦 +974",
  },
  {
    name: "Bhutan",
    code: "BT",
    emoji: "🇧🇹",
    dial_code: "+975",
    label: "🇧🇹 +975",
  },
  {
    name: "Mongolia",
    code: "MN",
    emoji: "🇲🇳",
    dial_code: "+976",
    label: "🇲🇳 +976",
  },
  {
    name: "Nepal",
    code: "NP",
    emoji: "🇳🇵",
    dial_code: "+977",
    label: "🇳🇵 +977",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    emoji: "🇹🇯",
    dial_code: "+992",
    label: "🇹🇯 +992",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    emoji: "🇹🇲",
    dial_code: "+993",
    label: "🇹🇲 +993",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    emoji: "🇦🇿",
    dial_code: "+994",
    label: "🇦🇿 +994",
  },
  {
    name: "Georgia",
    code: "GE",
    emoji: "🇬🇪",
    dial_code: "+995",
    label: "🇬🇪 +995",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    emoji: "🇰🇬",
    dial_code: "+996",
    label: "🇰🇬 +996",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    emoji: "🇺🇿",
    dial_code: "+998",
    label: "🇺🇿 +998",
  },
  {
    name: "Bahamas",
    code: "BS",
    emoji: "🇧🇸",
    dial_code: "+1242",
    label: "🇧🇸 +1242",
  },
  {
    name: "Barbados",
    code: "BB",
    emoji: "🇧🇧",
    dial_code: "+1246",
    label: "🇧🇧 +1246",
  },
  {
    name: "Anguilla",
    code: "AI",
    emoji: "🇦🇮",
    dial_code: "+1264",
    label: "🇦🇮 +1264",
  },
  {
    name: "Antigua & Barbuda",
    code: "AG",
    emoji: "🇦🇬",
    dial_code: "+1268",
    label: "🇦🇬 +1268",
  },
  {
    name: "British Virgin Islands",
    code: "VG",
    emoji: "🇻🇬",
    dial_code: "+1284",
    label: "🇻🇬 +1284",
  },
  {
    name: "U.S. Virgin Islands",
    code: "VI",
    emoji: "🇻🇮",
    dial_code: "+1340",
    label: "🇻🇮 +1340",
  },
  {
    name: "Bermuda",
    code: "BM",
    emoji: "🇧🇲",
    dial_code: "+1441",
    label: "🇧🇲 +1441",
  },
  {
    name: "Grenada",
    code: "GD",
    emoji: "🇬🇩",
    dial_code: "+1473",
    label: "🇬🇩 +1473",
  },
  {
    name: "Turks & Caicos Islands",
    code: "TC",
    emoji: "🇹🇨",
    dial_code: "+1649",
    label: "🇹🇨 +1649",
  },
  {
    name: "Montserrat",
    code: "MS",
    emoji: "🇲🇸",
    dial_code: "+1664",
    label: "🇲🇸 +1664",
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    emoji: "🇲🇵",
    dial_code: "+1670",
    label: "🇲🇵 +1670",
  },
  {
    name: "Guam",
    code: "GU",
    emoji: "🇬🇺",
    dial_code: "+1671",
    label: "🇬🇺 +1671",
  },
  {
    name: "American Samoa",
    code: "AS",
    emoji: "🇦🇸",
    dial_code: "+1684",
    label: "🇦🇸 +1684",
  },
  {
    name: "St. Lucia",
    code: "LC",
    emoji: "🇱🇨",
    dial_code: "+1758",
    label: "🇱🇨 +1758",
  },
  {
    name: "Dominica",
    code: "DM",
    emoji: "🇩🇲",
    dial_code: "+1767",
    label: "🇩🇲 +1767",
  },
  {
    name: "St. Vincent & Grenadines",
    code: "VC",
    emoji: "🇻🇨",
    dial_code: "+1784",
    label: "🇻🇨 +1784",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    emoji: "🇩🇴",
    dial_code: "+1849",
    label: "🇩🇴 +1849",
  },
  {
    name: "Trinidad & Tobago",
    code: "TT",
    emoji: "🇹🇹",
    dial_code: "+1868",
    label: "🇹🇹 +1868",
  },
  {
    name: "St. Kitts & Nevis",
    code: "KN",
    emoji: "🇰🇳",
    dial_code: "+1869",
    label: "🇰🇳 +1869",
  },
  {
    name: "Jamaica",
    code: "JM",
    emoji: "🇯🇲",
    dial_code: "+1876",
    label: "🇯🇲 +1876",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    emoji: "🇵🇷",
    dial_code: "+1939",
    label: "🇵🇷 +1939",
  },
];

export default PHONE_CODES_AND_LINKS;
