export default {
  tick: require('../../../assets/images/scanner/tick.png'),
  switch_off: require('../../../assets/images/scanner/switch_off.png'),
  switch_on: require('../../../assets/images/scanner/switch_on.png'),
  camera_icon: require('../../../assets/images/scanner/camera_icon.png'),
  white_back_arrow: require('../../../assets/images/icons/white_back_arrow.png'),
  black_back_arrow: require('../../../assets/images/icons/black_back_arrow.png'),
  accepted: require('../../../assets/images/onboarding/accepted.png'),
  failed: require('../../../assets/images/onboarding/failed.png'),
  show: require('../../../assets/images/login/show.png'),
  hide: require('../../../assets/images/login/hide.png'),
  un_checked: require('../../../assets/images/icons/un_checked.png'),
  checked_circle: require('../../../assets/images/icons/checked_circle.png'),
  green_camera: require('../../../assets/images/scanner/green_camera.png'),
  remove: require('../../../assets/images/scanner/remove.png'),
  grey_camera: require('../../../assets/images/scanner/grey_camera.png'),
  errorIcon: require('../../../assets/images/login/errorIcon.png'),
};
