export default {
  home_white: require('../../assets/images/icons/home_white.png'),
  slogan: require('../../assets/images/logos/slogan.png'),
  user: require('../../assets/images/icons/user.png'),
  info: require('../../assets/images/onboarding/info.png'),
  right_icon: require('../../assets/images/icons/right_icon.png'),
  back_arrow: require('../../assets/images/icons/back_arrow.png'),
  instruction1: require('../../assets/images/onboarding/instruction1.png'),
  instruction2: require('../../assets/images/onboarding/instruction2.png'),
  instruction3: require('../../assets/images/onboarding/instruction3.png'),
  digi_bank: require('../../assets/images/onboarding/digi_bank.png'),
  debit_card: require('../../assets/images/onboarding/debit_card.png'),
  cif: require('../../assets/images/onboarding/cif.png'),
  black_back_arrow: require('../../assets/images/icons/black_back_arrow.png'),
  instructions1: require('../../assets/images/onboarding/instructions1.png'),
  instructions2: require('../../assets/images/onboarding/instructions2.png'),
  instructions3: require('../../assets/images/onboarding/instructions3.png'),
  arrow_right: require('../../assets/images/onboarding/arrow_right.png'),
  show: require('../../assets/images/login/show.png'),
  hide: require('../../assets/images/login/hide.png'),
  cancel: require('../../assets/images/icons/cancel.png'),
  camera_icon: require('../../assets/images/scanner/camera_icon.png'),
  green_camera: require('../../assets/images/scanner/green_camera.png'),
  remove: require('../../assets/images/scanner/remove.png'),
  grey_camera: require('../../assets/images/scanner/grey_camera.png'),
  errorIcon: require('../../assets/images/login/errorIcon.png'),
  selectedRadio: require('../../assets/images/icons/selectedRadio.png'),
  unselectedRadio: require('../../assets/images/icons/unselectRadio.png'),
  instructIDcard1:require('../../assets/images/onboarding/instruct_id_card1.png'),
  instructIDcard2:require('../../assets/images/onboarding/instruct_id_card2.png'),
  instructIDcard3:require('../../assets/images/onboarding/instruct_id_card3.png'),
};
