export const TestIds = {
  registration_info: 'registration_info',
  registration_service_info: 'registration_service_info',
  unregistered_info: 'unregistered_info',
  existing_customers: 'existing_customers',
  heading: 'heading',
  title: 'title',
  image_icon: 'image_icon',
  checked_item: 'checked_item',
  authentication_process: 'authentication_process',
  gradient_button: 'gradient_button',
  heading_first: 'heading_first',
  heading_next: 'heading_next',
  back_button: 'back_button',
};
