export const TestIds = {
  name_list_item: 'name_list_item',
  on_press_no: 'on_press_no',
  on_press_yes: 'on_press_yes',
  close_modal: 'close_modal',
  cancel_modal: 'cancel_modal',
  step5_progress_bar: 'step5_progress_bar',
  step5_user_info: 'step5_user_info',
  user_info_modal: 'user_info_modal',
  gradient_button: 'gradient_button',
  heading_first: 'heading_first',
  heading_next: 'heading_next',
  back_button: 'back_button',
  heading_text: 'heading_text',
  have_id: 'have_id',
  no_id: 'no_id',
  instruction_id: 'instruction_id',
  info_id: 'info_id',
  purpose_id: 'purpose_id',
  selection_title_id: 'selection_title_id',
  render_item_id: 'render_item_id',
};
