export enum ROUTES {
  MAIN_APPLICATION = "MAIN_APPLICATION",
  GUEST_NAVIGATION = "GUEST_NAVIGATION",
}

export enum EMainAppScreenList {
  HOME_STACK_SCREEN = "HOME_STACK_SCREEN",
}

export enum EGuestScreenList {
  LOGIN_SCREEN = "LOGIN_SCREEN",
  ONBOARDING_SCREEN = "ONBOARDING_SCREEN",
}

export enum EOnBoardingScreenList {
  ONBOARDING_STEP_ONE_SCREEN = "ONBOARDING_STEP_ONE_SCREEN",
  ONBOARDING_STEP_TWO_SCREEN = "ONBOARDING_STEP_TWO_SCREEN",
  ONBOARDING_STEP_THREE_SCREEN = "ONBOARDING_STEP_THREE_SCREEN",
  ONBOARDING_SUCCESS_SCREEN = "ONBOARDING_SUCCESS_SCREEN",
}

export enum EHomeScreenList {
  HOME_SCREEN = "HOME_SCREEN",
  HOME_DETAIL_SCREEN = "HOME_DETAIL_SCREEN",
}
