export enum ELanguageOptions {
  "January" = "January",
  "February" = "February",
  "March" = "March",
  "April" = "April",
  "May" = "May",
  "June" = "June",
  "July" = "July",
  "August" = "August",
  "September" = "September",
  "October" = "October",
  "November" = "November",
  "December" = "December",
  "monday" = "monday",
  "tuesday" = "tuesday",
  "wednesday" = "wednesday",
  "thursday" = "thursday",
  "friday" = "friday",
  "saturday" = "saturday",
  "sunday" = "sunday",
}
